---
- name: Deploy to MyAWS
  hosts: myaws

  tasks:
  - name: Delete previous content
    file:
      state: absent
      path: /srv/www/projects.arkon.digital/threejs/chromatic-aberration-pp/

  - name: Recreate directory
    file:
      path: /srv/www/projects.arkon.digital/threejs/chromatic-aberration-pp
      state: directory

  - name: Upload latest build
    copy:
      src: ../dist/
      dest: /srv/www/projects.arkon.digital/threejs/chromatic-aberration-pp